version: "3.3"
services:
  ipsec-vpn-server:
    image: hwdsl2/ipsec-vpn-server
    env_file:
      - ./vpn-server-secret.env
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    volumes:
      - /lib/modules:/lib/modules:ro
    privileged: true