version: "3.3"
services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    env_file:
      - ./zabbix-server-secret.env
    volumes:
      - "/opt/configs/zabbix:/var/lib/zabbix"
    ports:
      - "10051:10051"
    networks:
      - zabbix
  mysql:
    image: mariadb:latest
    env_file:
      - ./mariadb-secret.env
    volumes:
      - "/opt/media/mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - zabbix
  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql:ubuntu-3.4-latest
    ports:
      - "8091:80"
    deploy:
      resources:
        limits:
          memory: 512m
    env_file:
      - ./zabbix-web-secret.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - zabbix
networks:
  zabbix:
    external: true