version: '3.3'

services:
  docker-compose:
    image: docker-compose
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 53:53
    volumes:
      - /var/log/unbound:/var/log/unbound
